### PR TITLE
Example of OTEL instrumentation w/pino and winston

### PR DESCRIPTION
**Pull request by BradPlayerZero**
Initial version for node using pino and winston 

Resolves ENG-4409 

This change is [Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1)

### CODE REVIEW

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 21 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1)* status: 21 of 27 files reviewed, 3 unresolved discussions (waiting on @BradPlayerZero)

___
*[`.idea/.gitignore` line 1 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-pjUhXAb7X_3ciSSCt:-O-pjUhXAb7X_3ciSSCu:bv4n972) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/746b1fe7f8bbef0c6d2308a53a8111dcebcc8266/.idea/.gitignore#L1)):*
> ```ignore
> # Default ignored files
> ```

Lets .gitignore the entire .idea folder as well as any other ide stuff
___
*[`client/package-lock.json` line 1 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-pjjDj7DQhywu36dpj:-O-pjjDk4Bd79eYgloX9:b-d314p0) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/746b1fe7f8bbef0c6d2308a53a8111dcebcc8266/client/package-lock.json#L1)):*
> ```JSON
> {
> ```

Lets exclude/.gitignore all package-lock.json and node_modules as well
___
*[`client/src/App.test.js` line 1 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-pjwiPBOtCsaiMJsK8:-O-pjwiPBOtCsaiMJsK9:b-xnedfs) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/746b1fe7f8bbef0c6d2308a53a8111dcebcc8266/client/src/App.test.js#L1)):*
> ```JavaScript
> import React from 'react';
> ```

Unsure we need/want any testing stuff in our example?

**Comment by BradPlayerZero** [comment]
*[`client/package-lock.json` line 1 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-pjjDj7DQhywu36dpj:-O-q06yN62kIwcOmj506:bih8l5c) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/746b1fe7f8bbef0c6d2308a53a8111dcebcc8266/client/package-lock.json#L1)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Lets exclude/.gitignore all package-lock.json and node_modules as well
</blockquote></details>

I don't think we should ignore package-lock.json.  Point is we want the software to work, may not work if user installs different versions of libraries.

**Comment by BradPlayerZero** [comment]
*[`client/package-lock.json` line 1 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-pjjDj7DQhywu36dpj:-O-qv0V44_7MTnDLRjiM:b-1d8tqy) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/746b1fe7f8bbef0c6d2308a53a8111dcebcc8266/client/package-lock.json#L1)):*
<details><summary><i>Previously, BradPlayerZero (Brad Morris) wrote…</i></summary><blockquote>

I don't think we should ignore package-lock.json.  Point is we want the software to work, may not work if user installs different versions of libraries.
</blockquote></details>

As agreed, I'll put package-lock.json in the .gitignore

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 27 files at r1, 8 of 8 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1)* status: all files reviewed, 2 unresolved discussions (waiting on @BradPlayerZero)

___
*[`client/package-lock.json` line 1 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-pjjDj7DQhywu36dpj:-O-ucobr5wJbmHqj56ZK:b-37b9wj) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/746b1fe7f8bbef0c6d2308a53a8111dcebcc8266/client/package-lock.json#L1)):*
<details><summary><i>Previously, BradPlayerZero (Brad Morris) wrote…</i></summary><blockquote>

As agreed, I'll put package-lock.json in the .gitignore
</blockquote></details>

Still needs to be removed from the git repo as well otherwise it is't actually removed :)
___
*[`server-winston/package-lock.json` line 0 at r3](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1#-O-uceLID6sC84dpDS_2:-O-uceLJ010Xo0MinwsH:b70yhag) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/53fd93572d0268a32b3501653dc1c5435cc38289/server-winston/package-lock.json#L0)):*
Still needs to be removed

**Review by sepatel — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BradPlayerZero)

**Pull request merged**
