### PR TITLE
Improve documentation, examples, and add .env settings

### PR DESCRIPTION
**Pull request by BradPlayerZero**
Resolves ENG-4424

- - -
This change is [Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2)

### CODE REVIEW

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2)* status: all files reviewed, 3 unresolved discussions (waiting on @BradPlayerZero)

___
*[`README.md` line 55 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2#-O0Et2xa5HZ8JTSD-crF:-O0Et2xa5HZ8JTSD-crG:b-e5rna2) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/d602be06c3371c5e43cc88e5949dc61ae3ce35eb/README.md#L55)):*
> ```Markdown
> // without resource we don't have proper service.name, service.version correlated with logs
>   resource: detectResourcesSync({
> // this have to be manually adjusted to match SDK OTEL_NODE_RESOURCE_DETECTORS
> ```

`has` for grammatical correctness.

Also can you provide the link showing the list of detectors they can utilize so they understand better what to adjust it to?



_Code quote:_
```Markdown
have
```
___
*[`README.md` line 56 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2#-O0EtgLT19puFZXCDIoi:-O0EtgLT19puFZXCDIoj:bosvkas) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/d602be06c3371c5e43cc88e5949dc61ae3ce35eb/README.md#L56)):*
> ```Markdown
>   resource: detectResourcesSync({
> // this have to be manually adjusted to match SDK OTEL_NODE_RESOURCE_DETECTORS
>     detectors: [envDetectorSync, processDetectorSync, hostDetectorSync],
> ```

Your example environment has 4 detectors, your example config here has only 3 of them?
___
*[`README.md` line 82 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2#-O0EtOdM8d3MGFfbYl37:-O0EtOdN93TpEpWEQHGR:b5127hq) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/d602be06c3371c5e43cc88e5949dc61ae3ce35eb/README.md#L82)):*
> ```Markdown
>             recordProcessorType: 'simple',
>             exporterOptions: { protocol: 'console' }
>           }
> ```

Do we want the sample that most people will copy/paste to also do the console? The winston one didn't include that by default, I'm not sure the pino should either then.

**Comment by BradPlayerZero** [comment]
*[`README.md` line 82 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2#-O0EtOdM8d3MGFfbYl37:-O0EuIHe6mdA9IvbIym0:b-xhcimz) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/d602be06c3371c5e43cc88e5949dc61ae3ce35eb/README.md#L82)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Do we want the sample that most people will copy/paste to also do the console? The winston one didn't include that by default, I'm not sure the pino should either then.
</blockquote></details>

Yes, we want console logging because they may have another log service we should not interfere with.  Winston does include a console log.  See server-winston/logger.js line 35.  Just not important in the adding instructions, as it assumes they have Winston already set up.

**Comment by BradPlayerZero** [comment]
*[`README.md` line 55 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2#-O0Et2xa5HZ8JTSD-crF:-O0FD-QOAp2nX5XVP4me:bk3rmrr) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/d602be06c3371c5e43cc88e5949dc61ae3ce35eb/README.md#L55)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

`has` for grammatical correctness.

Also can you provide the link showing the list of detectors they can utilize so they understand better what to adjust it to?
</blockquote></details>

I've now included a link, although there are just 4 resources now, as far as I can tell

**Comment by BradPlayerZero** [comment]
*[`README.md` line 56 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2#-O0EtgLT19puFZXCDIoi:-O0FD5ew5Wal62Xq8_bY:bt2vr1b) ([raw file](https://github.com/goplayerzero/open-telemetry-nodejs/blob/d602be06c3371c5e43cc88e5949dc61ae3ce35eb/README.md#L56)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Your example environment has 4 detectors, your example config here has only 3 of them?
</blockquote></details>

Fixed.

**Review by sepatel — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @BradPlayerZero)

**Review by sepatel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-nodejs/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BradPlayerZero)

**Pull request merged**
